2019-11-25 19:10:32,120 : kivy : Factory: 194 symbols loaded
2019-11-25 19:10:33,432 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-11-25 19:10:34,507 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-11-25 19:10:34,507 : kivy : Video: Provider: gstplayer
2019-11-25 19:10:35,178 : kivy : Loading MPF-MC controller
2019-11-25 19:10:35,193 : mpfmc : Mission Pinball Framework Media Controller v0.50.8
2019-11-25 19:10:35,193 : mpfmc : Mission Pinball Framework Game Engine v0.50.17
2019-11-25 19:10:35,193 : mpfmc : Machine path: D:\POKEMON - 3 - GYMS DISPLAYS
2019-11-25 19:10:35,193 : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\69e9e8261b2a7a7fe237ef0e6090f00e.mpf_cache
2019-11-25 19:10:36,952 : ConfigProcessor : Loading config from file c:\python34\lib\site-packages\mpfmc\mcconfig.yaml.
2019-11-25 19:10:37,199 : ConfigProcessor : Loading config: c:\python34\lib\site-packages\mpfmc\mcconfig.yaml
2019-11-25 19:10:37,199 : ConfigProcessor : Loading config from file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.
2019-11-25 19:10:37,268 : kivy : YAML error found in file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml. Line 89,Position 9: mapping values are not allowed here
  in "D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml", line 89, column 9
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 194, in load
    config = self.process(f)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 220, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\python34\lib\site-packages\ruamel\yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 57, in get_single_data
    node = self.get_single_node()
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 46, in get_single_node
    document = self.compose_document()
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 66, in compose_document
    node = self.compose_node(None, None)
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 156, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 97, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\python34\lib\site-packages\ruamel\yaml\composer.py", line 149, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "c:\python34\lib\site-packages\ruamel\yaml\parser_.py", line 118, in check_event
    self.current_event = self.state()
  File "c:\python34\lib\site-packages\ruamel\yaml\parser_.py", line 490, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "c:\python34\lib\site-packages\ruamel\yaml\scanner.py", line 130, in check_token
    self.fetch_more_tokens()
  File "c:\python34\lib\site-packages\ruamel\yaml\scanner.py", line 237, in fetch_more_tokens
    return self.fetch_value()
  File "c:\python34\lib\site-packages\ruamel\yaml\scanner.py", line 596, in fetch_value
    self.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml", line 89, column 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 189, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 95, in __init__
    self.machine_config = self._load_config()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 224, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 201, in load
    raise ValueError(msg)
ValueError: YAML error found in file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml. Line 89,Position 9: mapping values are not allowed here
  in "D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml", line 89, column 9
2019-11-25 19:10:37,321 : kivy : Stopping child threads... (0 remaining)
2019-11-25 19:10:37,337 : kivy : All child threads stopped.
