2019-05-27 10:47:05,455 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.17
2019-05-27 10:47:05,455 : INFO : Machine : Command line arguments: {'bcp': True, 'logfile': 'logs\\2019-05-27-10-47-05-mpf-DESKTOP-I5I6D25.log', 'syslog_address': None, 'no_load_cache': False, 'loglevel': 10, 'consoleloglevel': 10, 'pause': False, 'force_platform': None, 'create_config_cache': True, 'production': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'text_ui': True, 'mpfconfigfile': 'c:\\python34\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'mc_file_name': None}
2019-05-27 10:47:05,455 : INFO : Machine : MPF path: c:\python34\lib\site-packages\mpf
2019-05-27 10:47:05,455 : INFO : Machine : Machine path: D:\POKEMON
2019-05-27 10:47:05,455 : INFO : Machine : Platform: win32
2019-05-27 10:47:05,455 : INFO : Machine : Python executable location: c:\python34\python.exe
2019-05-27 10:47:05,455 : INFO : Machine : Python version: 3.4.4 (64-bit)
2019-05-27 10:47:07,322 : INFO : Machine : Machine config file #1: config.yaml
2019-05-27 10:47:07,334 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\d99dba3f33c3bdd270e8cf6c1a53f44e.mpf_cache
2019-05-27 10:47:07,364 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-27 10:47:07,423 : INFO : Machine : Initialise MPF.
2019-05-27 10:47:07,712 : DEBUG : FAST : Configuring FAST hardware.
2019-05-27 10:47:08,845 : INFO : FAST : Connecting to com4 at 921600bps
2019-05-27 10:47:08,892 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.01
2019-05-27 10:47:08,892 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.01', 'change': True, 'prev_value': None}
2019-05-27 10:47:08,892 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'change': True, 'prev_value': None}
2019-05-27 10:47:08,892 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-05-27 10:47:08,977 : INFO : FAST : Connecting to com5 at 921600bps
2019-05-27 10:47:09,008 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-05-27 10:47:09,008 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,008 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,014 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,446 : DEBUG : YAML File Interface : Loading file: D:\POKEMON\data/machine_vars.yaml
2019-05-27 10:47:09,524 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 189, 'change': True, 'prev_value': None}
2019-05-27 10:47:09,524 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.50.17', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,524 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.50.17, Config version:5, Show version: 5, BCP version:1.1', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,524 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.4.4', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.17134', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.17134', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'change': True, 'prev_value': None}
2019-05-27 10:47:09,540 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-27 10:47:10,310 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c8c985d122de6339937b15f5cde5ffe7.mpf_cache
2019-05-27 10:47:10,392 : DEBUG : ModeController : Loaded mode game
2019-05-27 10:47:10,401 : WARNING : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\01c5ea7020f20fc8cd2609416c749c9a.mpf_cache
2019-05-27 10:47:10,401 : INFO : ConfigProcessor : Loading config from file D:\POKEMON\modes\pichu\config\pichu.yaml.
2019-05-27 10:47:10,401 : DEBUG : YAML File Interface : Loading file: D:\POKEMON\modes\pichu\config\pichu.yaml
2019-05-27 10:47:10,474 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 9\'',)>) at c:\python34\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 9\'',)>) at c:\python34\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 194, in load
    config = self.process(f)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 220, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\python34\lib\site-packages\ruamel\yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 59, in get_single_data
    return self.construct_document(node)
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 68, in construct_document
    for dummy in generator:
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 481, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "text" was defined multiple times in config   in "D:\\POKEMON\\modes\\pichu\\config\\pichu.yaml", line 11, column 9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "c:\python34\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\python34\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\python34\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\python34\lib\site-packages\mpf\core\mode_controller.py", line 113, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\python34\lib\site-packages\mpf\core\mode_controller.py", line 262, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\python34\lib\site-packages\mpf\core\mode_controller.py", line 180, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 208, in load
    raise ValueError(msg)
ValueError: Error found in file D:\POKEMON\modes\pichu\config\pichu.yaml: 'Key "text" was defined multiple times in config   in "D:\\POKEMON\\modes\\pichu\\config\\pichu.yaml", line 11, column 9'
2019-05-27 10:47:11,094 : ERROR : root : Exception is not set.
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 661, in run
    self.initialise_mpf()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 653, in initialise_mpf
    if init.exception():
  File "c:\python34\lib\asyncio\futures.py", line 288, in exception
    raise InvalidStateError('Exception is not set.')
asyncio.futures.InvalidStateError: Exception is not set.
