2020-04-11 17:42:18,218 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.9
2020-04-11 17:42:18,218 : INFO : Machine : Command line arguments: {'configfile': ['config.yaml'], 'syslog_address': None, 'force_assets_load': False, 'logfile': 'logs\\2020-04-11-17-42-17-mpf-DESKTOP-I5I6D25.log', 'production': False, 'no_load_cache': False, 'consoleloglevel': 20, 'mc_file_name': None, 'loglevel': 15, 'bcp': True, 'force_platform': None, 'mpfconfigfile': 'c:\\users\\mission pinball\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'jsonlogging': False, 'pause': False, 'no_sound': False, 'text_ui': True, 'create_config_cache': True}
2020-04-11 17:42:18,218 : INFO : Machine : MPF path: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf
2020-04-11 17:42:18,218 : INFO : Machine : Machine path: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS
2020-04-11 17:42:18,218 : INFO : Machine : Platform: win32
2020-04-11 17:42:18,218 : INFO : Machine : Python executable location: c:\users\mission pinball\appdata\local\programs\python\python35\python.exe
2020-04-11 17:42:18,218 : INFO : Machine : Python version: 3.5.4 (64-bit)
2020-04-11 17:42:18,218 : INFO : Machine : Machine config file #1: config.yaml
2020-04-11 17:42:18,249 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1d59add9599c514c5f7c5be61c73be75.mpf_cache
2020-04-11 17:42:18,281 : INFO : Machine : Initialise MPF.
2020-04-11 17:42:19,327 : INFO : FAST : Connecting to com4 at 921600bps
2020-04-11 17:42:19,406 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.01
2020-04-11 17:42:19,406 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'change': True, 'value': '01.01', 'prev_value': None}
2020-04-11 17:42:19,406 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'change': True, 'value': 'FP-CPU-002-2', 'prev_value': None}
2020-04-11 17:42:19,406 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2020-04-11 17:42:19,515 : INFO : FAST : Connecting to com5 at 921600bps
2020-04-11 17:42:19,577 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2020-04-11 17:42:19,577 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'change': True, 'value': '01.00', 'prev_value': None}
2020-04-11 17:42:19,577 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'change': True, 'value': 'FP-CPU-002-2', 'prev_value': None}
2020-04-11 17:42:19,577 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'change': True, 'value': 'FREE PLAY', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'change': True, 'value': 107, 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'change': True, 'value': 'MPF v0.52.9', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'change': True, 'value': 'MPF v0.52.9, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'change': True, 'value': '3.5.4', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'change': True, 'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'change': True, 'value': 'Windows', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'change': True, 'value': '10', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'change': True, 'value': '10.0.18362', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'change': True, 'value': 'AMD64', 'prev_value': None}
2020-04-11 17:42:20,124 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-04-11 17:42:20,499 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5903aae11c08aba35176e5c1f4c1be59.mpf_cache
2020-04-11 17:42:20,531 : WARNING : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\5e332dad5466fb4d353f60c87864de4c.mpf_cache
2020-04-11 17:42:20,531 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\gym8\config\gym8.yaml.
2020-04-11 17:42:20,656 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\gym8\config\gym8.yaml
2020-04-11 17:42:20,656 : INFO : ConfigProcessor : Config file cache created: C:\Users\MISSIO~1\AppData\Local\Temp\5e332dad5466fb4d353f60c87864de4c.mpf_cache
2020-04-11 17:42:20,671 : WARNING : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\6dbb84b4a2bd3a6642f95ce5744c7797.mpf_cache
2020-04-11 17:42:20,671 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\raichu\config\raichu.yaml.
2020-04-11 17:42:20,952 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\raichu\config\raichu.yaml
2020-04-11 17:42:20,968 : INFO : ConfigProcessor : Config file cache created: C:\Users\MISSIO~1\AppData\Local\Temp\6dbb84b4a2bd3a6642f95ce5744c7797.mpf_cache
2020-04-11 17:42:20,999 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1a49828cb8454c90fd195e3886327b9d.mpf_cache
2020-04-11 17:42:21,046 : WARNING : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\5a22bfd3cd388f17bd2b6acbd36605ae.mpf_cache
2020-04-11 17:42:21,046 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\gym4\config\gym4.yaml.
2020-04-11 17:42:21,171 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\gym4\config\gym4.yaml
2020-04-11 17:42:21,171 : INFO : ConfigProcessor : Config file cache created: C:\Users\MISSIO~1\AppData\Local\Temp\5a22bfd3cd388f17bd2b6acbd36605ae.mpf_cache
2020-04-11 17:42:21,781 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\e316602f2754df2a40ebb1b620c83c27.mpf_cache
2020-04-11 17:42:21,827 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\dd4913724ea8e05b50af346c964d02e0.mpf_cache
2020-04-11 17:42:21,874 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c81a0f1062502e33bbed66b9eae15858.mpf_cache
2020-04-11 17:42:21,937 : WARNING : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\a79159ab091a1f38ad921bad9a429f77.mpf_cache
2020-04-11 17:42:21,937 : INFO : ConfigProcessor : Loading config from file c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2020-04-11 17:42:21,999 : INFO : ConfigProcessor : Loading config: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml
2020-04-11 17:42:21,999 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml.
2020-04-11 17:42:22,249 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-11 17:42:22,265 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ue)'}]}}}]",)>) at c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ue)'}]}}}]",)>) at c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 142, in _load_config_file_and_return_loaded_files
    raise ConfigFileError("Config should be a dict: {}".format(config), self.log.name, "ConfigProcessor")
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigProcessor: Config should be a dict: [{'duration': '20s', 'slides': {'show_high_scores': {'widgets': [{'text': 'HIGH SCORES', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-100'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'text': '(machine|score1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'text': '(machine|score1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'text': '(machine|score1_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'text': '(machine|score2_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'text': '(machine|score2_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'text': '(machine|score2_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'text': '(machine|score3_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'text': '(machine|score3_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'text': '(machine|score3_value)'}, {'text': 'LOOP CHAMPION', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-500'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'text': '(machine|loops1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'text': '(machine|loops1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'text': '(machine|loops1_value)'}]}}}] Error Code: CFE-ConfigProcessor-ConfigProcessor
2020-04-11 17:42:22,312 : INFO : Machine : Starting the main run loop.
2020-04-11 17:42:22,312 : INFO : Machine : Shutting down...
2020-04-11 17:42:22,327 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-04-11 17:42:22,343 : ERROR : FAST : Stop called on serial connection com5
2020-04-11 17:42:22,359 : ERROR : FAST : Stop called on serial connection com4
2020-04-11 17:42:22,624 : ERROR : root : Config File Error in ConfigProcessor: Config should be a dict: [{'duration': '20s', 'slides': {'show_high_scores': {'widgets': [{'text': 'HIGH SCORES', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-100'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'text': '(machine|score1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'text': '(machine|score1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'text': '(machine|score1_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'text': '(machine|score2_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'text': '(machine|score2_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'text': '(machine|score2_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'text': '(machine|score3_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'text': '(machine|score3_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'text': '(machine|score3_value)'}, {'text': 'LOOP CHAMPION', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-500'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'text': '(machine|loops1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'text': '(machine|loops1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'text': '(machine|loops1_value)'}]}}}] Error Code: CFE-ConfigProcessor-ConfigProcessor
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 709, in run
    self._run_loop()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_processor.py", line 142, in _load_config_file_and_return_loaded_files
    raise ConfigFileError("Config should be a dict: {}".format(config), self.log.name, "ConfigProcessor")
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigProcessor: Config should be a dict: [{'duration': '20s', 'slides': {'show_high_scores': {'widgets': [{'text': 'HIGH SCORES', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-100'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-200', 'text': '(machine|score1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-200', 'text': '(machine|score1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-200', 'text': '(machine|score1_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-240', 'text': '(machine|score2_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-240', 'text': '(machine|score2_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-240', 'text': '(machine|score2_value)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-280', 'text': '(machine|score3_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-280', 'text': '(machine|score3_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-280', 'text': '(machine|score3_value)'}, {'text': 'LOOP CHAMPION', 'type': 'Text', 'bold': True, 'font_size': 60, 'anchor_x': 'center', 'x': 'center', 'anchor_y': 'center', 'y': 'top-500'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'y': 'top-600', 'text': '(machine|loops1_label)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'y': 'top-600', 'text': '(machine|loops1_name)'}, {'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'y': 'top-600', 'text': '(machine|loops1_value)'}]}}}] Error Code: CFE-ConfigProcessor-ConfigProcessor
