2020-04-11 22:24:45,062 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.9
2020-04-11 22:24:45,062 : INFO : Machine : Command line arguments: {'force_platform': None, 'force_assets_load': False, 'mc_file_name': None, 'logfile': 'logs\\2020-04-11-22-24-44-mpf-DESKTOP-I5I6D25.log', 'loglevel': 15, 'mpfconfigfile': 'c:\\users\\mission pinball\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'text_ui': True, 'syslog_address': None, 'bcp': True, 'no_load_cache': False, 'configfile': ['config.yaml'], 'no_sound': False, 'consoleloglevel': 20, 'jsonlogging': False, 'create_config_cache': True, 'production': False, 'pause': False}
2020-04-11 22:24:45,062 : INFO : Machine : MPF path: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf
2020-04-11 22:24:45,062 : INFO : Machine : Machine path: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS
2020-04-11 22:24:45,062 : INFO : Machine : Platform: win32
2020-04-11 22:24:45,062 : INFO : Machine : Python executable location: c:\users\mission pinball\appdata\local\programs\python\python35\python.exe
2020-04-11 22:24:45,062 : INFO : Machine : Python version: 3.5.4 (64-bit)
2020-04-11 22:24:45,078 : INFO : Machine : Machine config file #1: config.yaml
2020-04-11 22:24:45,078 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1d59add9599c514c5f7c5be61c73be75.mpf_cache
2020-04-11 22:24:45,093 : INFO : Machine : Initialise MPF.
2020-04-11 22:24:45,625 : INFO : FAST : Connecting to com4 at 921600bps
2020-04-11 22:24:45,687 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.01
2020-04-11 22:24:45,687 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.01', 'change': True, 'prev_value': None}
2020-04-11 22:24:45,687 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'change': True, 'prev_value': None}
2020-04-11 22:24:45,687 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2020-04-11 22:24:45,781 : INFO : FAST : Connecting to com5 at 921600bps
2020-04-11 22:24:45,843 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2020-04-11 22:24:45,843 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'change': True, 'prev_value': None}
2020-04-11 22:24:45,843 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'change': True, 'prev_value': None}
2020-04-11 22:24:45,843 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 107, 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.52.9', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.52.9, Config version:5, Show version: 5, BCP version:1.1', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.5.4', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'change': True, 'prev_value': None}
2020-04-11 22:24:46,365 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-04-11 22:24:46,584 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\0db36da4b9aa41dcdeae696ef4ec8d87.mpf_cache
2020-04-11 22:24:46,599 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\e316602f2754df2a40ebb1b620c83c27.mpf_cache
2020-04-11 22:24:46,615 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\8e537f3f1075ad5ff3f7e8ba8228812c.mpf_cache
2020-04-11 22:24:46,630 : WARNING : ConfigProcessor : Config file in cache changed: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-11 22:24:46,630 : INFO : ConfigProcessor : Loading config from file c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2020-04-11 22:24:46,630 : INFO : ConfigProcessor : Loading config: c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\modes\attract\config\attract.yaml
2020-04-11 22:24:46,646 : INFO : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml.
2020-04-11 22:24:46,771 : INFO : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-11 22:24:46,771 : INFO : ConfigProcessor : Config file cache created: C:\Users\MISSIO~1\AppData\Local\Temp\a79159ab091a1f38ad921bad9a429f77.mpf_cache
2020-04-11 22:24:46,802 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5b0c10fb1ea3d696f3389c798402fbbd.mpf_cache
2020-04-11 22:24:46,834 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5a22bfd3cd388f17bd2b6acbd36605ae.mpf_cache
2020-04-11 22:24:46,849 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\ead1ab3e53925d446b3cb0becf429113.mpf_cache
2020-04-11 22:24:46,865 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\b9fac23b74e0b513c055e4621b74ad7e.mpf_cache
2020-04-11 22:24:46,880 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\f9a13da868835514a4e555019188716d.mpf_cache
2020-04-11 22:24:46,896 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\4c74177f109f95ed9599c78880646655.mpf_cache
2020-04-11 22:24:46,927 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\d6bb1cdfa60c1f50f35785cba55875d1.mpf_cache
2020-04-11 22:24:46,943 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\4ea733655e2f71aef4d6f646b7999fe0.mpf_cache
2020-04-11 22:24:46,959 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\2476b3e7b98dcc7e56449320299b63be.mpf_cache
2020-04-11 22:24:46,974 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\0378f93b62c546ad0a14fc16b8462c41.mpf_cache
2020-04-11 22:24:46,990 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5e23017ae2bff2a0239ff499da948ac3.mpf_cache
2020-04-11 22:24:47,005 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c81a0f1062502e33bbed66b9eae15858.mpf_cache
2020-04-11 22:24:47,021 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\6dbb84b4a2bd3a6642f95ce5744c7797.mpf_cache
2020-04-11 22:24:47,037 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\47fed2ef5afbaf0c19527a565aa191d9.mpf_cache
2020-04-11 22:24:47,052 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5903aae11c08aba35176e5c1f4c1be59.mpf_cache
2020-04-11 22:24:47,068 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\3183d529c1c05723ae7f7f27f6d76374.mpf_cache
2020-04-11 22:24:47,084 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\5e332dad5466fb4d353f60c87864de4c.mpf_cache
2020-04-11 22:24:47,099 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\c721f48534ae43d3f9c4e17312560aaa.mpf_cache
2020-04-11 22:24:47,130 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\dd4913724ea8e05b50af346c964d02e0.mpf_cache
2020-04-11 22:24:47,146 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\201769dfbc23cf51d44452c1bfe1f92e.mpf_cache
2020-04-11 22:24:47,162 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\b51fa6c1189029eac07bf57001e3c2a0.mpf_cache
2020-04-11 22:24:47,177 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\1a49828cb8454c90fd195e3886327b9d.mpf_cache
2020-04-11 22:24:47,193 : INFO : ConfigProcessor : Loading config from cache: C:\Users\MISSIO~1\AppData\Local\Temp\32e6b619402cb4da5981e97ecb1f6408.mpf_cache
2020-04-11 22:24:47,287 : INFO : EventManager : Event: ======'drop_target_bank_right_bank_up'====== Args={}
2020-04-11 22:24:47,302 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2020-04-11 22:24:47,302 : INFO : SwitchController : Found active switch: (('11', 1), <Platform.FAST>)
2020-04-11 22:24:47,365 : ERROR : ConfigValidator : Your config contains a value for the setting "show_player:show_high_scores", but this is not a valid setting name.
2020-04-11 22:24:47,365 : ERROR : asyncio : Exception in callback EventManager._done(<Task finishe...lue)'}]}}}",)>)
handle: <Handle EventManager._done(<Task finishe...lue)'}]}}}",)>)>
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 34, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 60, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 128, in _parse_config
    return self.get_full_config(config)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 201, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_validator.py", line 238, in validate_config
    validation_failure_info)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_validator.py", line 398, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "show_player:show_high_scores", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 690, in _done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 102, in initialise_modes
    mode.initialise_mode()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode.py", line 594, in initialise_mode
    **item.kwargs)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 134, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 106, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 37, in validate_config_entry
    name, self.show_section, settings), 1, self.log.name) from e
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in show_player: Failed to load config player mode_attract_started:shows {'slides': {'show_high_scores': {'widgets': [{'y': 'top-100', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'HIGH SCORES'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score1_label)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score1_name)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score1_value)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score2_label)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score2_name)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score2_value)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score3_label)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score3_name)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score3_value)'}, {'y': 'top-500', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'LOOP CHAMPION'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|loops1_label)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|loops1_name)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|loops1_value)'}]}}} Error Code: CFE-show_player-1
2020-04-11 22:24:47,490 : INFO : Machine : Starting the main run loop.
2020-04-11 22:24:47,490 : INFO : Machine : Shutting down...
2020-04-11 22:24:47,490 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-04-11 22:24:47,505 : ERROR : FAST : Stop called on serial connection com5
2020-04-11 22:24:47,505 : ERROR : FAST : Stop called on serial connection com4
2020-04-11 22:24:47,755 : ERROR : root : Config File Error in show_player: Failed to load config player mode_attract_started:shows {'slides': {'show_high_scores': {'widgets': [{'y': 'top-100', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'HIGH SCORES'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score1_label)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score1_name)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score1_value)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score2_label)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score2_name)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score2_value)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score3_label)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score3_name)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score3_value)'}, {'y': 'top-500', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'LOOP CHAMPION'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|loops1_label)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|loops1_name)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|loops1_value)'}]}}} Error Code: CFE-show_player-1
Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 34, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 60, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 128, in _parse_config
    return self.get_full_config(config)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 201, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_validator.py", line 238, in validate_config
    validation_failure_info)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_validator.py", line 398, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "show_player:show_high_scores", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 709, in run
    self._run_loop()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 690, in _done
    future.result()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode_controller.py", line 102, in initialise_modes
    mode.initialise_mode()
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\mode.py", line 594, in initialise_mode
    **item.kwargs)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 134, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\core\config_player.py", line 106, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\mission pinball\appdata\local\programs\python\python35\lib\site-packages\mpf\config_players\device_config_player.py", line 37, in validate_config_entry
    name, self.show_section, settings), 1, self.log.name) from e
mpf.exceptions.ConfigFileError.ConfigFileError: Config File Error in show_player: Failed to load config player mode_attract_started:shows {'slides': {'show_high_scores': {'widgets': [{'y': 'top-100', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'HIGH SCORES'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score1_label)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score1_name)'}, {'y': 'top-200', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score1_value)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score2_label)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score2_name)'}, {'y': 'top-240', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score2_value)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|score3_label)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|score3_name)'}, {'y': 'top-280', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|score3_value)'}, {'y': 'top-500', 'font_size': 60, 'anchor_x': 'center', 'bold': True, 'anchor_y': 'center', 'type': 'Text', 'x': 'center', 'text': 'LOOP CHAMPION'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_label', 'text': '(machine|loops1_label)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_name', 'text': '(machine|loops1_name)'}, {'y': 'top-600', 'type': 'Text', 'style': 'attract_mode_high_score_display_score', 'text': '(machine|loops1_value)'}]}}} Error Code: CFE-show_player-1
